#!/bin/bash

#Warning: hostname -A adds a space to the end of returned value(s)
FQDN=$(hostname -A | sed -e /\ /s///g)
FROM="<ZimbreMailServer@$FQDN"
EMAIL="AJREPO@example.com"
Z_BASE_DIR="/opt/zimbra"
X3_FILE=$Z_BASE_DIR/ssl/letsencrypt/lets-encrypt-x3-cross-signed.pem.txt

MESSAGE_FILE="/tmp/message.txt"

echo "Subject: Letsencrypt Renewal of Zimbra Cert done
From: <$FROM>

Zimbra Certificate Renewal done
This message generated by /etc/letsencrypt/renewal-hooks/deploy/ajonotify.sh" > $MESSAGE_FILE

TODAY=$(date +%Y%m%d)

#Make Backup Directory
mkdir -p "$Z_BASE_DIR/ssl/letsencrypt/bak.$TODAY"
if [[ $(  mkdir -p "$Z_BASE_DIR/ssl/letsencrypt/bak.$TODAY") -ne 0 ]]; then
  echo "Subject: ERROR: Letsencrypt Renewal of Zimbra Cert
From: <$FROM>

  Unable to make backup directory" > $MESSAGE_FILE
  cat $MESSAGE_FILE | $Z_BASE_DIR/common/sbin/sendmail -t "$EMAIL"
  exit 1
fi
chown zimbra:zimbra "$Z_BASE_DIR/ssl/letsencrypt/bak.$TODAY"


#Backup Old Cert
if [[ $(cp $Z_BASE_DIR/ssl/letsencrypt/*.pem $Z_BASE_DIR/ssl/letsencrypt/bak."$TODAY"/) -ne 0 ]]; then
  echo "Subject: ERROR: Letsencrypt Renewal of Zimbra Cert
From: <$FROM>

  Unable to backup old Certiricate, stopping" > $MESSAGE_FILE
  cat $MESSAGE_FILE | $Z_BASE_DIR/common/sbin/sendmail -t "$EMAIL"
  exit 1
fi

#Copy New Cert
if [[ $(cp /etc/letsencrypt/live/"$FQHN"/* $Z_BASE_DIR/ssl/letsencrypt/) -ne 0 ]]; then
  echo "Subject: ERROR: Letsencrypt Renewal of Zimbra Cert
From: <$FROM>

  Unable to copy new Certiricate to $Z_BASE_DIR/ssl/letsencrypt, stopping" > $MESSAGE_FILE
  cat $MESSAGE_FILE | $Z_BASE_DIR/common/sbin/sendmail -t "$EMAIL"
  exit 1
fi

#Chaining Cert
#https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem.txt
#https://letsencrypt.org/certs/letsencryptauthorityx3.pem.txt
X3CERTURI="https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem.txt"
#X3 Cert chaining
if [[ $(curl -o /tmp/lets-encrypt-x3-cross-signed.pem.txt $X3CERTURI) -ne 0 ]]; then
  echo "Subject: WARNING: Letsencrypt Renewal of Zimbra Cert
From: <$FROM>

  Unable to download X3 Cross Signed Cert" > $MESSAGE_FILE
  cat $MESSAGE_FILE | $Z_BASE_DIR/common/sbin/sendmail -t "$EMAIL"
fi

if [[ -f "$X3_FILE" ]]; then
  #compare to see if X3 Cert changed
  if [[ $(diff /tmp/lets-encrypt-x3-cross-signed.pem.txt $X3_FILE) -ne 0 ]]; then
    echo "Subject: WARNING: X3 cert download differs from previous X3 cert
From: <$FROM>

    The downloaded X3 Cross Signed Cert differs from what was saved previously. 
    This might be ok if this is the first time you've run this program or if it actually changed
    but letting you know anyway."
else
  cp /tmp/lets-encrypt-x3-cross-signed.pem.txt $Z_BASE_DIR/ssl/letsencrypt/ 
  chown zimbra:zimbra $X3_FILE
fi

if [[ -f "$X3_FILE" && -f "$Z_BASE_DIR/opt/zimbra/ssl/letsencrypt/chain.pem" ]]; then
  cat $X3_FILE >> $Z_BASE_DIR/ssl/letsencrypt/chain.pem
  chown zimbra:zimbra /opt/zimbra/ssl/letsencrypt/*
else
  echo "Subject: ERROR: Letsencrypt Renewal of Zimbra Cert
From: <$FROM>

  $X3_FILE or chain.pem file missing. stopping" > $MESSAGE_FILE
  cat $MESSAGE_FILE | $Z_BASE_DIR/common/sbin/sendmail -t "$EMAIL"
  exit 1
fi

cat $MESSAGE_FILE | $Z_BASE_DIR/common/sbin/sendmail -t "$EMAIL"
